### ISSUE TITLE
'startAfter' KeyError in status.json

### ISSUE THREAD

**Issue by akifoss** [acorg/slurm-pipeline#18]
$ slurm-pipeline-status.py -s status.json

gives this:

Traceback (most recent call last):
File "/scratch/tcj25/root/.virtualenvs/35/bin/slurm-pipeline-status.py", line 55, in
print(status.toStr(args.squeueArgs))
File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/slurm_pipeline/status.py", line 153, in toStr
if specification['startAfter']:
KeyError: 'startAfter'

The 'startAfter' key is added to the specification in slurm_pipeline/pipeline.py in the schedule method. There's a test for it in test/test_pipeline.py (line 1385). However, it is neither included in the specification.json file, nor in the final status.json file, and yet appears as a KeyError.

**Comment by terrycojones** [comment]
I'm not sure what's going on here. It might be that the status file used was an old one, with no `startAfter` key.
