### ISSUE TITLE
Is slurm-pipeline compatible with dependent job arrays?

### ISSUE THREAD

**Issue by andrewsanchez** [acorg/slurm-pipeline#21]
Currently working my way through the documentation and am wondering if slurm-pipeline is compatible with dependent job arrays?  Eg, something that might be submitted like so:

```bash
$ sbatch job_array.sh
Submitted batch job 1222012

$ sbatch --dependency=afterok:1222012_5 job_array2.sh 
```

**Comment by andrewsanchez** [comment]
Is this what using the `collect` option in the specification file is used to accomplish?

**Comment by terrycojones** [comment]
Hi Andrew.  Yes, dependencies like that are handled properly. In the JSON spec you would indicate that `job_array2.sh` depends on `job_array.sh` finishing. `slurm-pipeline.py` will set an environment variable (`SP_DEPENDENCY_ARG`) that you use in the second sbatch invocation. It basically boils down to putting `sbatch $SP_DEPENDENCY_ARG ...` in your script. There are some examples in the README and the `examples` dir.

**Comment by terrycojones** [comment]
I just added a file, `talk-slides.pdf` which might make it clearer what a `collect` step does.

**Comment by andrewsanchez** [comment]
Wonderful!  Thanks so much, @terrycojones  Looking forward to using this in my project https://github.com/andrewsanchez/NCBITK which is a bit of a mess right now.

**Comment by terrycojones** [comment]
You're welcome. Let me know if you have more questions, etc. I'll close this ticket. You can always re-open it :-)
