### ISSUE TITLE
submit multiple jobs in different nodes and collect results after all nodes finished

### ISSUE THREAD

**Issue by LujingF** [acorg/slurm-pipeline#40]
Hi,
Is the slurm-pipeline can submit jobs automatically? I found it couldn't submit jobs by itself when I try to run your examples. For the blast example, I thought it would be split the file into several smaller files and executable files, after that the slurm-pipeline would submit  all executable files to slurm clusters. At last, the slurm-pipeline would collect all results after all jobs were finished. Is it possible to achieve this goal by using these scripts?

**Comment by terrycojones** [comment]
Hi. The slurm-pipeline code doesn't work at that level. It submits jobs for you, takes care of being able to tell SLURM about dependencies, and can show you the status of jobs spread over many nodes, etc., but it doesn't know anything about the actual computation taking place.

So if you need to split up FASTQ, run BLAST, and put the results back together, that's up to you. I mean you have to write the scripts to do that.  One example of something similar is at https://github.com/acorg/eske-blastn-pipeline-spec

Also, the BLAST example in the slurm-pipeline examples directory isn't real. It doesn't really run BLAST and it doesn't submit any SLURM jobs. It's just a simple example to give a framework of what that would look like. A real example is the URL above.

Hope that helps!
