### ISSUE TITLE
slurm-pipeline.py: error: unrecognized arguments: texts/1-karamazov.txt texts/2-trial.txt texts/3-ulysses.txt

### ISSUE THREAD

**Issue by avatar-lavventura** [acorg/slurm-pipeline#41]
I am trying to run `word-count` example.

I have run following line from the `README`:

```
$ cd examples/word-count
$ slurm-pipeline.py -s specification.json texts/*.txt > status.json
```

Generates following error:

```
usage: slurm-pipeline.py [-h] --specification specification.json [--force]
                         [--firstStep step-name] [--lastStep step-name]
                         [--skip step-name] [--sleep SLEEP]
                         [--startAfter [STARTAFTER [STARTAFTER ...]]]
                         [--nice NICE] [--output [OUTPUT]]
                         [--scriptArgs SCRIPTARGS [SCRIPTARGS ...]]
slurm-pipeline.py: error: unrecognized arguments: texts/1-karamazov.txt texts/2-trial.txt texts/3-ulysses.txt
```

I think it should be `slurm-pipeline.py --specification specification.json --scriptArgs texts/*.txt > status.json` on Readme, `--scriptArgs` was missing.

**Comment by terrycojones** [comment]
Hi. You're missing `--scriptArgs` before `texts/*.txt`. If you run `make` you should see the correct call.  If not, please let me know. The latest is version 3.0.1, just in case you have something else:

```sh
$ env PYTHONPATH=. bin/slurm-pipeline-version.py
3.0.1
```

Thanks!

Terry

**Comment by terrycojones** [comment]
I just read your description more closely and have now also fixed `README.md` and pushed `3.0.2` to PyPI. Thanks again :-)
