### ISSUE TITLE
If a job cancelled can we re-queue that job and continue pipeline?

### ISSUE THREAD

**Issue by avatar-lavventura** [acorg/slurm-pipeline#44]
`Slurm` has a `requeue` option, [usage example](https://stackoverflow.com/a/50613999/2402577):

Based on following [answer][1] and [guide][2] 29th section, it is recommended to use `scontrol requeue $jobID`, that will re-queue the already cancelled job.

> if job crashes can be detected from within the submission script, and crashes are random, you can simply requeue the job with scontrol requeue $SLURM_JOB_ID so that it runs again.

-----------

**=>** For example I am running `word-count` example or on the any pipeline and some task is cancelled and a job that depends on that cancelled job could not be continue and halted, since its dependent job never completed.

Later, is it possible to `requeue` that cancelled job and continue the pipeline from where its halted instead of running pipeline from beginning?

  [1]: https://stackoverflow.com/a/44758889/2402577
  [2]: https://slurm.schedmd.com/faq.html#req

**Comment by terrycojones** [comment]
Hi. Sorry for the slow reply. This is really a SLURM question, and I don't know the answer! It's a good question - I didn't even consider that it might be possible to re-queue cancelled jobs. When my pipelines fail for some reason I usually just restart them using the `--firstStep` option to `slurm-pipeline.py`.  You may be able to restart them manually. The `slurm-pipeline-status.py` command might help you there in getting the job ids - I could probably add a `--printCancelled` option to it.
